---
- name: "Lab 1, Sesion 5: Registros"
  hosts: nodo01
  vars:
    fichero: "/tmp/datos_horarios_{{ ansible_facts['hostname'] }}.txt"
  
  tasks:
    - name: "Guarda la hora (hh:mm:ss) actual en un registro"
      command: "date +%T"
      register: hora_pre
      # Ejecutamos con "ansible-playbook playbook.yml -v" para ver el formato de salida => hora_pre.stdout_lines[0]

    - name: "Cambia la hora del nodo01 a Europe/Moscow y guarda la salida en un registro"
      timezone:
        name: Europe/Moscow
      register: cambio_tz
      when: >
        ( ansible_date_time.weekday_number == "1" or
          ansible_date_time.weekday_number == "3" or 
          ansible_date_time.weekday_number == "5"
        ) and ansible_date_time.hour >= "12"

    - name: "Cambia la hora del nodo01 a Asia/Tokio y guarda la salida en un registro"
      timezone:
        name: Asia/Tokyo
      register: cambio_tztokio
      when: not cambio_tz.changed

    - name: "Guarda la hora (hh:mm:ss) actual en un registro"
      command: "date +%T"
      register: hora_post

    - name: "Escribe en {{ fichero }} la diferencia de horas para Europe/Moscow"
      blockinfile:
        path: "{{ fichero }}"
        create: yes
        block: |
          La zona horaria antes del cambio es {{ cambio_tz.diff.before.name }} Y la hora era {{ hora_pre.stdout_lines[0] }}
          La zona horaria despues del cambio es {{ cambio_tz.diff.after.name }} Y la hora era {{ hora_post.stdout_lines[0] }}
      when: cambio_tz.changed

    - name: "Escribe en {{ fichero }} la diferencia de horas para Asia/Tokyo"
      blockinfile:
        path: "{{ fichero }}"
        create: yes
        block: |
          La zona horaria antes del cambio es {{ cambio_tztokio.diff.before.name }} Y la hora era {{ hora_pre.stdout_lines[0] }}
          La zona horaria despues del cambio es {{ cambio_tztokio.diff.after.name }} Y la hora era {{ hora_post.stdout_lines[0] }}
      when: cambio_tztokio.changed

    - name: "Restaura la zona horaria inicial para Europe/Moscow"
      timezone:
        name: "{{ cambio_tz.diff.before.name }}"
      when: cambio_tz.changed
      # Comprobar con
      # timedatectl | grep "Time zone"
      # En caso de error:
      # timedatectl set-timezone Europe/Madrid

    - name: "Restaura la zona horaria inicial para Asia/Tokyo"
      timezone:
        name: "{{ cambio_tztokio.diff.before.name }}"
      when: cambio_tztokio.changed
...